model: ollama:gemma2:27b
clients:
- type: ollama
  api_base: http://127.0.0.1:11434
  api_auth: null
  models:
  - name: llama3.1:latest
    max_input_tokens: 131072
  - name: aya:latest
    max_input_tokens: 8192
  - name: codestral:latest
    max_input_tokens: 32768
  - name: gemma2:27b
    max_input_tokens: 8192
  - name: gemma2:27b-instruct-q5_0
    max_input_tokens: 8192
  - name: gemma2:latest
    max_input_tokens: 8192
  - name: codegemma:latest
    max_input_tokens: 8192
  - name: codellama:13b
    max_input_tokens: 16384
  - name: codeqwen:latest
    max_input_tokens: 65536
  - name: falcon2:latest
    max_input_tokens: 2048
  - name: deepseek-coder-v2:latest
    max_input_tokens: 163840
  - name: granite-code:8b
    max_input_tokens: 4096
  - name: wizard-vicuna-uncensored:13b
    max_input_tokens: 2048
  - name: mixtral:latest
    max_input_tokens: 2048
  - name: phi3:medium
    max_input_tokens: 4096
  - name: llama3:latest
    max_input_tokens: 8192
  - name: llama3:latest
    max_input_tokens: 8192
  - name: mistral-nemo:latest
    max_input_tokens: 128000
  - name: llama3.1:8b
    max_input_tokens: 131072
    type: embedding
    output_vector_size: 4096
    default_chunk_size: 16000
  - name: avr/sfr-embedding-mistral:latest
    max_input_tokens: 32768
    type: embedding
    output_vector_size: 4096
    default_chunk_size: 3000
  - name: gemma2:27b-instruct-q5_0
    max_input_tokens: 8192
    type: embedding
    output_vector_size: 4608
    default_chunk_size: 3000
  - name: aya:35b
    max_input_tokens: 8192
  - name: aya:35b
    max_input_tokens: 8192
    type: embedding
    output_vector_size: 8192
    default_chunk_size: 3000




# Define document loaders to control how RAG and `.file`/`--file` load files of specific formats.
document_loaders:
  # You can add custom loaders using the following syntax:
  #   <file-extension>: <command-to-load-the-file>
  # Note: Use `$1` for input file and `$2` for output file. If `$2` is omitted, use stdout as output.
  pdf: 'pdftotext $1 -'                         # Load .pdf file, see https://poppler.freedesktop.org
  docx: 'pandoc --to markdown $1'                  # Load .docx file
  # xlsx: 'ssconvert $1 $2'                     # Load .xlsx file
  # html: 'pandoc --to markdown $1'                # Load .html file
